Update server_test.py
spotify/luigi pull request #3279
Opened 2024-02-28 15:43 UTC by eltociear

## Description

beging -> beginning

2024-02-29 03:48 UTC, dlstadther requested changes
Pretty sure the comment should be `begin`, not `beginning`.

Also, appears that something CI dependencies is causing tests to fail (saw this with another PR a few days ago too). Unsure when I'll have the time to investigate further.

2024-08-26 09:52 UTC, pablocasares approved these changes

2024-08-26 11:19 UTC, dlstadther approved these changes

2024-08-26 11:20 UTC, dlstadther commented
Rerunning failed tests to see if transient

2024-08-26 11:47 UTC, merged