add ChoiceListParameter
spotify/luigi pull request #3305
Opened 2024-09-02 13:13 UTC by kitagry

## Description

A parameter type complementary to ChoiceParameter that allows for an arbitrarily sized list (0 to n).

## Motivation and Context

Convenient addition to the Luigi parameter type inventory.

## Have you tested this? If so, how?
 

I have included unit tests.

2024-09-06 15:05 UTC, dlstadther requested changes

2024-09-06 15:05 UTC, dlstadther commented on test/choice_list_parameter_test.py
> +class ChoiceListParameterTest(unittest.TestCase):
These tests should be put into `test/parameter_test.py`

2024-09-06 15:05 UTC, dlstadther commented on luigi/parameter.py
> +class ChoiceListParameter(Parameter):
This is fine with me with one exception. If this class is intended to be a multi-select of `ChoiceParameter`, it's counter to object-oriented for it to not inherit from `ChoiceParameter` (or a common Choice-based parent) such for them to maintain alignment of their choice parsing and validation.

What are your thoughts?

2024-09-16 07:12 UTC, kitagry commented
@dlstadther Thank you for the review! and I'm sorry for the late response.

I fixed test and ListChoiceParameter inheritance.

2024-09-24 21:18 UTC, dlstadther approved these changes

2024-09-24 21:18 UTC, merged

2024-09-26 00:23 UTC, kitagry commented
Thank you!